### ISSUE TITLE
Breaks eclipse auto-completion

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#1]
Hi there!

I have been using the vanilla lombok project with much success and when stumbled upon this I immediately decided to test it out, as it has further facilities. Unfortunately, if I replace the lombok.jar in my project and Eclipse home with your jar, I lose Eclipse auto-completion. 

I get the following popup:
Problems during Content Assist
The 'org.eclipse.jdt.ui.JavaAllCompletionProposalComputer' proposal computer from the 'org.eclipse.jdt.ui' plugi-in did not complete normally. The extension has thrown an exception.

The eclipse log contains the following:
!ENTRY org.eclipse.jdt.ui 2 0 2011-09-07 11:11:02.863
!MESSAGE The 'org.eclipse.jdt.ui.JavaAllCompletionProposalComputer' proposal computer from the 'org.eclipse.jdt.ui' plug-in did not complete normally. The extension has thrown a runtime exception.
!STACK 0
java.lang.NullPointerException
    at lombok.eclipse.agent.PatchExtensionMethod.getClassScope(PatchExtensionMethod.java:260)
    at lombok.eclipse.agent.PatchExtensionMethod.getExtensionMethods(PatchExtensionMethod.java:181)
    at lombok.eclipse.agent.PatchExtensionMethod.getJavaCompletionProposals(PatchExtensionMethod.java:169)
    at org.eclipse.jdt.ui.text.java.CompletionProposalCollector.getJavaCompletionProposals(CompletionProposalCollector.java:342)
    at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.internalComputeCompletionProposals(JavaCompletionProposalComputer.java:257)
    at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.computeCompletionProposals(JavaCompletionProposalComputer.java:206)
    at org.eclipse.jdt.internal.ui.text.java.JavaTypeCompletionProposalComputer.computeCompletionProposals(JavaTypeCompletionProposalComputer.java:61)
    at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:318)
    at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:267)
    at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:283)
    at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:243)
    at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1830)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:556)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:553)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:488)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:482)
    at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:377)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4140)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3757)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2696)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2660)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2494)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:674)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:667)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)

Hopefully this will help you fix this issue.

**Comment by nicholas22** [comment]
Just to update, I have confirmed a few times that putting the vanilla lombok.jar back fixes the problem and when using lombok-pg.jar re-introduces it...

**Comment by peichhorn** [comment]
Thanks for your feedback.
I've noticed this bug too and fix it few days ago.
I guess a should update the project jars.

**Comment by nicholas22** [comment]
Hi, thanks for your reply, I look forward to the update!

**Comment by peichhorn** [comment]
Uploading as we speak, the file has still the same version literal '0.10.0' as I like to use the same version lombok releases with.

**Comment by peichhorn** [comment]
Sorry shouldn't have closed the issue right away.
Please let me know if you still experience this behavior.

**Comment by nicholas22** [comment]
Yes there is still an issue. I'm downloading the lombok-pg-0.10.0 JAR (it says updated 15 mins ago so I assume that's the right one to download), but the same issue occurs. 

I did an MD5 sum on the previous and the uploaded file and they are the same! Maybe the wrong one was inadvertently uploaded?

**Comment by peichhorn** [comment]
I've uploaded it again, just in case I really screwed up there.

**Comment by nicholas22** [comment]
I'm getting the same MD5 on the lombok-pg-0.10.0.jar (from https://github.com/peichhorn/lombok-pg/downloads) as the version I downloaded before submitting this issue. This either means that the JARs were up to date already and this is a bug on the latest version, or that something else is going on (perhaps I'm downloading the wrong thing)

**Comment by peichhorn** [comment]
Can you try again, please? I just added a potential fix.

**Comment by nicholas22** [comment]
Could you also update the JAR? I'm not building from source. The current 0.10.0 version has the same MD5 as before opening this issue (hence it does not have the fix). Many thanks for your help!

**Comment by nicholas22** [comment]
Whoops: wrong button. Re-opened this issue...

**Comment by peichhorn** [comment]
I've uploaded it already, are you sure they have the same md5?
Cause md5sum (linux command) gives me two differende checksums.

**Comment by nicholas22** [comment]
Maybe I'm doing something wrong. I've tried http://cloud.github.com/downloads/peichhorn/lombok-pg/lombok-pg-0.10.0.jar and https://github.com/downloads/peichhorn/lombok-pg/lombok-pg-0.10.0.jar and they both give me an MD5 of a92aea1481c94a6450cc91b73a9bbc0e which is what I've been seeing all day. If this is the update, I'm still getting the error message, unfortunately.

**Comment by peichhorn** [comment]
Just downloaded the file again and got: f67221016e1669aa5aa0d7d960235dd2 MD5

**Comment by nicholas22** [comment]
I just got home and my openSuse gives a different MD5 (not the one you mentioned). Anyway, I tried it and it works! Let me try it on my work PC and let you know how it goes there. Many thanks!

**Comment by nicholas22** [comment]
Yes! It works :)

**Comment by ghost** [comment]
lombok_1.14.4 breaks Eclipse the same way, as in autocomplete gets broken if installed.

When I remove lombok parameters from eclipse.ini, everything gets back to normal

-javaagent:lombok.jar
-Xbootclasspath/a:lombok.jar
