### ISSUE TITLE
Newest edge release has eclipse autocomplete bug

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#23]
Hi Philipp, the latest edge release causes an auto-completion error (observed on a static method call on a class not imported yet). This does not appear to be happening for instance methods. Reverting to Friday's release for now.

!MESSAGE java.lang.NullPointerException
!STACK 0
java.lang.NullPointerException
    at org.eclipse.jdt.internal.compiler.parser.Parser.getMethodBodies(Parser.java:8689)
    at lombok.eclipse.agent.Patches.completeNode(Patches.java:115)
    at lombok.eclipse.agent.PatchFunction.onClassScope_buildFieldsAndMethods(PatchFunction.java:59)
    at org.eclipse.jdt.internal.compiler.lookup.ClassScope.buildFieldsAndMethods(ClassScope.java)
    at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildFieldsAndMethods(CompilationUnitScope.java:64)
    at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:208)
    at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:233)
    at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.accept(CompilationUnitProblemFinder.java:121)
    at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:150)
    at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:183)
    at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:487)
    at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findSingleImport(CompilationUnitScope.java:541)
    at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInImports(CompilationUnitScope.java:369)
    at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:466)
    at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:906)
    at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:194)
    at org.eclipse.jdt.internal.core.CompilationUnit.buildStructure(CompilationUnit.java:195)
    at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:258)
    at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:518)
    at org.eclipse.jdt.internal.core.CompilationUnit.makeConsistent(CompilationUnit.java:1079)
    at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:170)
    at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:89)
    at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:728)
    at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:788)
    at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1244)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:126)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.access$0(JavaReconcilingStrategy.java:108)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:89)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:87)
    at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:151)
    at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:86)
    at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:104)
    at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:77)
    at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:206)

**Comment by peichhorn** [comment]
For now I'm unable to reproduce it. Could you provide a small example.

**Comment by nicholas22** [comment]
Sure. 
1) Create a new project, 
2) reference the edge lombok.jar
3) Ensure the edge lombok is used as eclipse agent.
4) Restart eclipse
5) Create a package called test, create a class called Test in it
6) Create a package called main, create a class called Test1 in it
7) Add a public static void main(String[] args) to Test1. 
8) Without importing Test in Test1, inside the main write Test and press dot(.), the autocompletion error should come up. 

Hope this helps, otherwise I can try uploading to a file sharing site when I get home.

**Comment by peichhorn** [comment]
Did everything step by step, but no such 'luck', everything worked fine..

**Comment by nicholas22** [comment]
Hmm I can consistently reproduce it, let me upload it somewhere when I get the chance

**Comment by nicholas22** [comment]
I've sent you an email

**Comment by peichhorn** [comment]
Thx, I tried it but couldn't reproduce the stacktrace you posted above, but I got this one (which I've already fixed but not uploaded yesterday):

```
java.lang.ClassCastException: org.eclipse.jdt.internal.compiler.lookup.ProblemBinding cannot be cast to org.eclipse.jdt.internal.compiler.lookup.TypeBinding
    at lombok.eclipse.agent.PatchExtensionMethod.getFirstParameterType(PatchExtensionMethod.java:253)
    at lombok.eclipse.agent.PatchExtensionMethod.getExtensionMethods(PatchExtensionMethod.java:202)
    at lombok.eclipse.agent.PatchExtensionMethod.getJavaCompletionProposals(PatchExtensionMethod.java:180)
    at org.eclipse.jdt.ui.text.java.CompletionProposalCollector.getJavaCompletionProposals(CompletionProposalCollector.java:342)
    at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.internalComputeCompletionProposals(JavaCompletionProposalComputer.java:257)
    at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.computeCompletionProposals(JavaCompletionProposalComputer.java:206)
    at org.eclipse.mylyn.internal.java.ui.editor.FocusedJavaAllProposalComputer.computeCompletionProposals(FocusedJavaAllProposalComputer.java:96)
    at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:318)
    at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:267)
    at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:283)
    at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:243)
    at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1830)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:556)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:553)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:488)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:482)
    at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:377)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4140)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3757)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2696)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2660)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2494)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:674)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:667)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
```

I've uploaded a new file where said fix is present. Now everything works fine, like I said earlier this day.

**Comment by nicholas22** [comment]
OK I will test the latest in the coming week and see if it persists... Thanx

**Comment by peichhorn** [comment]
Thing is I'm still interested in the stacktrace you posted above, because this NPE you got there is really, really weird and could only mean that the eclipse parser was not properly initialized, which again is really, really weird. Maybe I don't the same stacktrace because I use a different version of eclipse.

I'm using:

Version: Indigo Release
Build id: 20110615-0604

Which version are you using?

**Comment by nicholas22** [comment]
It's the same:

Eclipse IDE for Java Developers
Version: Indigo Release
Build id: 20110615-0604

**Comment by nicholas22** [comment]
Hmm I got this consistently replicated across multiple PCs so I wonder what the deal is ...

**Comment by nicholas22** [comment]
Closing this, fixed in the latest version :)
