### ISSUE TITLE
javac support for @ExtensionMethod

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#25]
I'm running a continuous integration server which is Ant-based and the javac compiler does not work with @ExtensionMethod. How difficult would it be to port the ecj implementation to javac for this particularly cool annotation?

**Comment by peichhorn** [comment]
This is weird since I'm using automated integration tests for all the extensions and everything looks fine.
It's possible that I messed up the resolved types, because that's about the only thing in javac I can't cover with the unit test.

**Comment by nicholas22** [comment]
I thought it might be weird, it could be the crappy vcs we are forced to use, I will flush everything and try again then let you know. Thanks.

**Comment by peichhorn** [comment]
Since I couldn't let it go, I did a quick test in Netbeans with JDK 1.6,  1.7. And what can I say, they both love `@ExtensionMethod`. xD

**Comment by nicholas22** [comment]
Yes there is a problem unfortunately, the good news is I've narrowed it down quite a bit (I hope). The problem occurs when using extension methods 1) within super constructor calls and 2) static final fields. Examples:

1) super(name, new Character('A').to(new Character('Z')).join(new Character('1').to(new Character('9'))).toList()
2) private static final char[] ALPHABET = new Character('A').to(new Character('Z')).unbox();

I can confirm what you've said, there is no problem when using them elsewhere in code.

Error messages:

...cannot find symbol:
[16:58:19]: [javac] symbol : method to(java.lang.Character)

**Comment by peichhorn** [comment]
Good job, I will look into it. Btw really nice examples.

**Comment by nicholas22** [comment]
Ah thanks :)
Feel free to use it: https://github.com/nicholas22/jpropel-light

**Comment by peichhorn** [comment]
As always I've uploaded a new lombok-pg.jar (edge release)

**Comment by nicholas22** [comment]
I think this is not fully fixed for some reason, i'm getting:

[12:19:28]: [javac] error: Lombok annotation handler class lombok.javac.handlers.HandleExtensionMethod failed on MyClass.java: java.lang.NullPointerException
[12:19:28]: [javac] java.lang.NullPointerException
[12:19:28]: [javac] at lombok.javac.handlers.ast.JavacResolver$2.resolveMember(JavacResolver.java:50)
[12:19:28]: [javac] at lombok.javac.handlers.ast.JavacResolver$3.resolveMember(JavacResolver.java:59)
[12:19:28]: [javac] at lombok.javac.handlers.HandleExtensionMethod$ExtensionMethodReplaceVisitor.handleMethodCall(HandleExtensionMethod.java:156)
[12:19:28]: [javac] at lombok.javac.handlers.HandleExtensionMethod$ExtensionMethodReplaceVisitor.visitMethodInvocation(HandleExtensionMethod.java:147)
[12:19:28]: [javac] at lombok.javac.handlers.HandleExtensionMethod$ExtensionMethodReplaceVisitor.visitMethodInvocation(HandleExtensionMethod.java:131)
[12:19:28]: [javac] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1222)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:61)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:75)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:83)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.visitNewClass(TreeScanner.java:259)
[12:19:28]: [javac] at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1273)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:61)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.visitThrow(TreeScanner.java:239)
[12:19:28]: [javac] at com.sun.tools.javac.tree.JCTree$JCThrow.accept(JCTree.java:1164)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:61)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:75)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:143)
[12:19:28]: [javac] at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:748)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:61)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:65)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.visitCatch(TreeScanner.java:204)
[12:19:28]: [javac] at com.sun.tools.javac.tree.JCTree$JCCatch.accept(JCTree.java:1000)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:61)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:75)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:83)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.visitTry(TreeScanner.java:197)
[12:19:28]: [javac] at com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:977)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:61)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:65)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:75)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:143)
[12:19:28]: [javac] at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:748)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:61)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:65)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:127)
[12:19:28]: [javac] at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:660)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:61)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:65)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scan(TreeScanner.java:75)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:83)
[12:19:28]: [javac] at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:117)
[12:19:28]: [javac] at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:592)
[12:19:28]: [javac] at lombok.javac.handlers.HandleExtensionMethod$ExtensionMethodReplaceVisitor.replace(HandleExtensionMethod.java:142)
[12:19:28]: [javac] at lombok.javac.handlers.HandleExtensionMethod.handle(HandleExtensionMethod.java:89)
[12:19:28]: [javac] at lombok.javac.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:80)
[12:19:28]: [javac] at lombok.javac.HandlerLibrary.handleAnnotation(HandlerLibrary.java:184)
[12:19:28]: [javac] at lombok.javac.JavacTransformer$AnnotationVisitor.visitAnnotationOnType(JavacTransformer.java:92)
[12:19:28]: [javac] at lombok.javac.JavacNode.traverse(JavacNode.java:105)
[12:19:28]: [javac] at lombok.javac.JavacAST.traverseChildren(JavacAST.java:121)
[12:19:28]: [javac] at lombok.javac.JavacNode.traverse(JavacNode.java:68)
[12:19:28]: [javac] at lombok.javac.JavacAST.traverseChildren(JavacAST.java:121)
[12:19:28]: [javac] at lombok.javac.JavacNode.traverse(JavacNode.java:63)
[12:19:28]: [javac] at lombok.javac.JavacAST.traverse(JavacAST.java:116)
[12:19:28]: [javac] at lombok.javac.JavacTransformer.transform(JavacTransformer.java:73)
[12:19:28]: [javac] at lombok.javac.apt.Processor.process(Processor.java:217)
[12:19:28]: [javac] at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:117)
[12:19:28]: [javac] at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:169)
[12:19:28]: [javac] at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:625)
[12:19:28]: [javac] at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:554)
[12:19:28]: [javac] at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:699)
[12:19:28]: [javac] at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:981)
[12:19:28]: [javac] at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:727)
[12:19:28]: [javac] at com.sun.tools.javac.main.Main.compile(Main.java:353)
[12:19:28]: [javac] at com.sun.tools.javac.main.Main.compile(Main.java:279)
[12:19:28]: [javac] at com.sun.tools.javac.main.Main.compile(Main.java:270)
[12:19:28]: [javac] at com.sun.tools.javac.Main.compile(Main.java:69)
[12:19:28]: [javac] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:19:28]: [javac] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[12:19:28]: [javac] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[12:19:28]: [javac] at java.lang.reflect.Method.invoke(Method.java:597)
[12:19:28]: [javac] at org.apache.tools.ant.taskdefs.compilers.Javac13.execute(Javac13.java:56)
[12:19:28]: [javac] at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1134)
[12:19:28]: [javac] at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:912)
[12:19:28]: [javac] at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[12:19:28]: [javac] at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
[12:19:28]: [javac] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[12:19:28]: [javac] at java.lang.reflect.Method.invoke(Method.java:597)
[12:19:28]: [javac] at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[12:19:28]: [javac] at org.apache.tools.ant.Task.perform(Task.java:348)
[12:19:28]: [javac] at org.apache.tools.ant.Target.execute(Target.java:390)
[12:19:28]: [javac] at org.apache.tools.ant.Target.performTasks(Target.java:411)
[12:19:28]: [javac] at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
[12:19:28]: [javac] at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
[12:19:28]: [javac] at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[12:19:28]: [javac] at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
[12:19:28]: [javac] at org.apache.tools.ant.Main.runBuild(Main.java:809)
[12:19:28]: [javac] at org.apache.tools.ant.Main.startAnt(Main.java:217)
[12:19:28]: [javac] at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[12:19:28]: [javac] at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

**Comment by nicholas22** [comment]
I don't think I used to get this error in that class before, I hope it can be fixed by tomorrow otherwise I'll be forced to pull @ExtensionMethod usages from our project :'(

**Comment by peichhorn** [comment]
I will definitely look into this after work.

**Comment by nicholas22** [comment]
That's very re-assuring :) thanks!

**Comment by peichhorn** [comment]
This looks like a major bug in lombok. My guess is this is related to [issue 281](http://code.google.com/p/projectlombok/issues/detail?id=281) . So let me update lombok to 0.10.1 real quick, maybe this does the trick already.

**Comment by nicholas22** [comment]
OK I hope it works :)

**Comment by peichhorn** [comment]
Guess what? That did it. New jar coming to you soon. ;)

**Comment by peichhorn** [comment]
OK new file is up, now please, please tell me that it works. ;)

**Comment by nicholas22** [comment]
Damn, OK that has broken @Data and @Getter/@Setter unfortunately, i.e. I have lost my getters and setters. It's probably my fault for asking it in such short notice. Just take your time, I'll postpone extension methods until its properly done for javac :)

**Comment by peichhorn** [comment]
Damn I accidentally left some work-in-progress stuff in the @Data handler, while creating separate patch-files of my local lombok changes. Give me 10 minutes and the new file are up.

**Comment by peichhorn** [comment]
Files are up. If it's too late I'm sorry. Guess I should run all the tests of lombok and lombok-pg with the jar files in the future before uploading them.

Quick note on what happened as it is a nice opportunity to give some details about the guts of lombok:
Lombok annotation handers and all the other transformers are registered as service provider. 
For example if you look into the file 'META-INF\services\lombok.eclipse.EclipseAnnotationHandler' in the lombok.jar, you can see, as the name suggests, all eclipse annotation handlers. Now to automatically generate the service files lombok uses a spi library that allows you to expose any class as a Service by annotating it like this:

```
@ProviderFor(EclipseAnnotationHandler.class)
public class HandleData extends EclipseAnnotationHandler<Data> {
```

Now accidentally I've commented out the `@ProviderFor`  annotation, which makes `lombok.eclipse.handler.HandleData` disappear from the service file and therefore when using lombok there was no eclipse annotation handler for `@Data`.

Again I'm sorry, I will adjust my 'release'-process accordingly.

**Comment by nicholas22** [comment]
Seems to have done the trick and just in time ;) 
Thanks very much Philipp!
