### ISSUE TITLE
@Function compilation bug

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#89]
I'm getting a compilation error when building with Gradle, in a @Function annotated method:
(I believe it uses Javac though)

``` java
    /**
     * Parses a String subscription to a concrete object
     */
    @Function
    @SneakyThrows
    private static SourceSubscription parse(String subscription)
    {
      try
      {
        val parts = StringUtils.split(subscription, CONSTANT.HYPHEN);
        if (parts.length != 2)
          throw new IllegalArgumentException();

        return new SourceSubscription(parts[0], parts[1]);
      }
      catch(Exception e)
      {
        throw new IllegalArgumentException("Invalid subscription: " + subscription);
      }
    }
```

The work-around is to manually code:

``` java
    /**
     * Parses a String subscription to a concrete object
     */
    @SneakyThrows
    private static Function1<String, SourceSubscription> parse()
    {
      return new Function1<String, SourceSubscription>() {

        @Override
        public SourceSubscription apply(String subscription)
        {
          try
          {
            val parts = StringUtils.split(subscription, CONSTANT.HYPHEN);
            if (parts.length != 2)
              throw new IllegalArgumentException();

            // return new
            return new SourceSubscription(parts[0], parts[1]); 
          }
          catch(Exception e)
          {
            throw new IllegalArgumentException("Invalid subscription: " + subscription);
          }
        }
      };
    }
```

The error I get is:

java.lang.NullPointerException
        at com.sun.tools.javac.comp.MemberEnter.getMethodEnv(MemberEnter.java:65
8)
        at lombok.javac.JavacResolution$EnvFinder.visitMethodDef(JavacResolution
.java:292)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:639)
        at lombok.javac.JavacResolution.resolveMethodMember(JavacResolution.java
:325)
        at lombok.javac.handlers.HandleVal.visitLocal(HandleVal.java:96)
        at lombok.javac.JavacNode.traverse(JavacNode.java:92)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:122)
        at lombok.javac.JavacNode.traverse(JavacNode.java:98)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:122)
        at lombok.javac.JavacNode.traverse(JavacNode.java:98)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:122)
        at lombok.javac.JavacNode.traverse(JavacNode.java:98)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:122)
        at lombok.javac.JavacNode.traverse(JavacNode.java:98)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:122)
        at lombok.javac.JavacNode.traverse(JavacNode.java:77)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:122)
        at lombok.javac.JavacNode.traverse(JavacNode.java:67)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:122)
        at lombok.javac.JavacNode.traverse(JavacNode.java:98)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:122)
        at lombok.javac.JavacNode.traverse(JavacNode.java:98)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:122)
        at lombok.javac.JavacNode.traverse(JavacNode.java:77)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:122)
        at lombok.javac.JavacNode.traverse(JavacNode.java:67)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:122)
        at lombok.javac.JavacNode.traverse(JavacNode.java:62)
        at lombok.javac.JavacAST.traverse(JavacAST.java:117)
        at lombok.javac.HandlerLibrary.callASTVisitors(HandlerLibrary.java:211)
        at lombok.javac.JavacTransformer.transform(JavacTransformer.java:73)
        at lombok.javac.apt.Processor.process(Processor.java:217)
        at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationPro
cessor.java:117)
        at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:169)

**Comment by peichhorn** [comment]
Thanks for the example. I will look into it.

**Comment by peichhorn** [comment]
fixed it.. also added a test for this scenario.. man I really need to work on a concept of prioritizing lombok handlers..

**Comment by peichhorn** [comment]
I've deployed a new [lombok-pg 0.11.1-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/github/peichhorn/lombok-pg/0.11.1-SNAPSHOT).

**Comment by nicholas22** [comment]
That was quick! Thanks xD
